const Constants ={
    ADD_ACTIVITY:"ADD_ACTIVITY",
    HIDE_ACTIVITY:"HIDE_ACTIVITY",
    COMMENT_ACTIVITY:"COMMENT_ACTIVITY",
    ADD_FAVORITE:"ADD_FAVORITE",
    REMOVE_FAVORITE:"REMOVE_FAVORITE",
    ADD_MOVIE:"ADD_MOVIE",
    RATE_MOVIE:"RATE_MOVIE"
}

export default Constants